### ISSUE TITLE
Synergykit.sendNotification - implement parameters in docs

### ISSUE THREAD

**Issue by centi** [Letsgood/synergykit-sdk-nodejs#2]
Now this method sends only the userIds to the endpoint URL. There is no way to send the notification text or other parameters specified in documentation: https://synergykit.com/en/documentation/rest-api#send-notification

**Comment by centi** [comment]
I see you've already done this, thanks! But I found a little bug (typo) in the new implementation, in synergykit.js: https://github.com/Letsgood/synergykit-sdk-nodejs/blob/master/lib/synergykit.js#L191

The condition should have `user.get("_id")` instead of `users.get("_id")`.

**Comment by Neklan** [comment]
Solved in version 1.2.1
